@startuml
class Kunde {
-navn
-orderHistorie
-kortNummer

~HentHistorie()
}

class Menu{
-List<Produkt>
}

class Produkt {
-navn
}

class Online {
~StartOdre()
}

class IButik{
~StartOdre()
}

class Ordre {

}

class BestillingsOversigt {

}

class ForbrugOversigt {

}


Produkt "1" --* "*" Menu
Menu "1" --* "*" Kunde
Kunde "1" --* "*" Online
Kunde "1" --* "*" IButik
Online "1" --* "*" Ordre
IButik "1" --* "*" Ordre
Ordre "1" --> "*" BestillingsOversigt
BestillingsOversigt "1" --* "*" ForbrugOversigt
@enduml
