@startuml
Pizza "1" -* "*" Produkt
Ordre --> BestillingsOversigt
Produkt "1" --* "*" Menu
Menu "1" --* "*" Kunde
Kunde "1" --* "*" Online
Kunde "1" --* "*" IButik
Online "1" --* "*" Ordre
IButik "1" --* "*" Ordre
BestillingsOversigt --* OrdreFærdig
OrdreFærdig --* ForbrugOversigt
@enduml
