@startuml
left to right direction
skinparam packageStyle rectangle
actor Customer
actor Alfonso

rectangle "Mario's Pizzaria"{
  (TyperInd) <--Alfonso
  Customer --> (Menu)
  (Menu) -> (Order)
  (Order) --> Alfonso
  (ForbrugOversigt) <-- Alfonso
}
@enduml