@startuml
left to right direction
skinparam packageStyle rectangle
actor Customer
actor Alfonso

rectangle "Mario's Pizzaria"{
  Customer --> (Menu)
  Customer --> (Butik)
  (Online) <. (Order)
  (Butik) .> (Order)
  Customer --> (Online)

  (Order) --> Alfonso
  (ForbrugOversigt) <-- Alfonso
}
@enduml